import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  hhbotSidebar: [
    { type: 'doc', id: 'intro', label: 'Overview' },
    { type: 'autogenerated', dirName: 'HH-Bot' }, // change to '.' if HH-Bot docs are directly in docs/hhbot/
  ],
};

export default sidebars;
