import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // 🔝 TOP ROOT LINKS (must exist)
    {
      type: 'doc',
      id: 'intro',
      label: 'Overview',
    },
    {
      type: 'doc',
      id: 'HH-101/Board Basics Tasks/Jetson-board-introduction',
      label: 'Jetson Basics',
    },

    // 📘 HH-101 ROOT
    {
      type: 'category',
      label: 'HH-101',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'HH-101',
        },
      ],
    },

    // 🤖 HH-Bot ROOT
    {
      type: 'category',
      label: 'HH-Bot',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'HH-Bot',
        },
      ],
    },
  ],
};

export default sidebars;
