import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  hh101Sidebar: [{ type: 'autogenerated', dirName: 'HH-101' }],
};

export default sidebars;
